apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-fe
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: todo-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: todo-app
          image: tsubekti/todo-app-fe:v5
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"