apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        resources:
          limits:
            cpu: "600m"
            memory: "600Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: /data/db 
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
