apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-be
spec:
  selector:
    matchLabels:
      app: todo-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: todo-app
          image: tsubekti/todo-app-be:v3
          ports:
            - name: http
              containerPort: 80